#!/bin/bash
set -xe

#Dependencies
mongo localhost:27017/feedlark script/vagrant/create_feed_user_db.js
python dbtools/getter/getter.py &
go run dbtools/start_workers.go &

#Unit tests
python aggregator/testing.py
